# Generated by Django 2.0.3 on 2018-03-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('usr_id', models.IntegerField(default=12, primary_key=True, serialize=False, unique=True)),
                ('usr_name', models.CharField(max_length=65)),
                ('eml', models.CharField(max_length=50, unique=True)),
                ('pss', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
